"""Build data/params/nonleg_motor_forces.csv: torque per spike for the motor neurons
of the head, proboscis, antennae, abdomen, wings and halteres (session 12 B; switch
motor_unit:nonleg|torque_source = 1). Until now every one of them used the shared
motor_unit:all|force_per_spike (10 uN*mm, guessed), which at rest pins the head,
rostrum and antennae at their joint limits (runs/s12/nonleg/census_s12.json).

No measured force, cross-section or moment arm exists for any non-leg Drosophila
muscle (docs/research/s12_nonleg_muscle_sources.md). The only measured single-spike
motor-unit forces in the fly are the tibia flexor's (Azevedo et al. 2020 eLife
9:e56754, Fig 4): fast ~10 uN (1 unit), intermediate ~1 uN (3), slow <0.1 uN (9;
0.05 taken), measured at the tibia. The rule, the same convention as the leg table
(scripts/motor_forces.py: torque = force x length of the segment the joint moves):

  torque per spike = F_unit x lever
  F_unit = pool-mean twitch of the tibia flexor = (10 + 3x1 + 9x0.05)/13 = 1.035 uN
           (derived from the measured classes); bounds 0.05-10 uN, the measured
           slow-to-fast range
  lever  = length of the moved part on the flybody mesh, joint to far end
           (data/derived/nonleg_joint_geometry_flybody.csv; derived)

Assumptions (inferred, not measured): non-leg motor units span the same twitch-force
range as leg units and, without a size order for them, each takes the pool mean;
the output force acts at the far end of the moved part, as the leg anchor was
measured at the tibia. For the wing the steering muscles act through the hinge, so
the wing length overstates their lever. Twitch decay stays at the shared 30 ms
(guessed; the leg's fast/intermediate value).

    uv run python scripts/build_nonleg_forces.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
GEOM = REPO / "data" / "derived" / "nonleg_joint_geometry_flybody.csv"
OUT = REPO / "data" / "params" / "nonleg_motor_forces.csv"
AZ = "Azevedo et al. 2020 eLife 9:e56754 (Fig 4, Results)"
CLASSES = {"fast": (10.0, 1), "intermediate": (1.0, 3), "slow": (0.05, 9)}
F_MEAN = sum(f * n for f, n in CLASSES.values()) / sum(n for _, n in CLASSES.values())
F_LOW, F_HIGH = 0.05, 10.0

# group, actuator regex (actuator name without the "fly/" prefix), moved part(s), note
GROUPS = [
    ("head", r"^c_thorax-c_head-", ["c_head"], "neck muscles; yaw, roll and pitch share one lever"),
    ("proboscis_rostrum", r"^c_head-c_rostrum-", ["c_rostrum"], ""),
    ("proboscis_haustellum", r"^c_rostrum-c_haustellum-", ["c_haustellum"], ""),
    ("proboscis_labrum", r"^c_haustellum-[lr]_labrum-", ["l_labrum", "r_labrum"], "left/right mean"),
    ("antenna", r"^c_head-[lr]_antenna-", ["l_antenna", "r_antenna"], "left/right mean"),
    *[(f"abdomen{k}", rf"^c_(?:thorax|abdomen{k - 1})-c_abdomen{k}-", [f"c_abdomen{k}"], "")
      for k in range(1, 8)],
    ("wing", r"^c_thorax-[lr]_wing-", ["l_wing", "r_wing"],
     "steering muscles act through the hinge, so the wing length overstates the lever; "
     "the flight motor replaces these torques while flight power is on"),
    ("haltere", r"^c_thorax-[lr]_haltere-", ["l_haltere", "r_haltere"], "left/right mean"),
]


def main() -> None:
    g = pd.read_csv(GEOM, comment="#").set_index("child")
    rows = []
    for group, rx, parts, note in GROUPS:
        lever = float(g.loc[parts, "child_len_mm"].mean())
        rows.append(dict(
            group=group, actuator_regex=rx, torque_uNmm=round(F_MEAN * lever, 4), twitch_tau_ms="",
            basis="inferred", lever_mm=round(lever, 4), force_uN=round(F_MEAN, 4),
            low=round(F_LOW * lever, 4), high=round(F_HIGH * lever, 4),
            derivation=(f"tibia-flexor pool-mean single-spike twitch {F_MEAN:.3f} uN (derived from measured "
                        f"classes 10/1/0.05 uN x 1/3/9 units) x moved-part length {lever:.3f} mm (flybody mesh, "
                        f"derived); transfer from leg to this muscle group inferred"),
            source=f"{AZ}; data/derived/nonleg_joint_geometry_flybody.csv",
            uncertainty=("no measured force for any non-leg Drosophila muscle; bounds are the measured "
                         "slow-to-fast unit range 0.05-10 uN x the same lever" + (f"; {note}" if note else ""))))
    df = pd.DataFrame(rows)
    head = ("# Non-leg torque per spike per muscle group (session 12 B; switch motor_unit:nonleg|torque_source 1). "
            "Generated by scripts/build_nonleg_forces.py; see its docstring for the rule and assumptions. "
            "uN*mm; twitch_tau_ms blank = shared value.\n")
    OUT.write_text(head + df.to_csv(index=False))
    print(df[["group", "lever_mm", "torque_uNmm", "low", "high"]].to_string(index=False))


if __name__ == "__main__":
    main()
