"""Per-presynaptic-type conduction delay from skeleton path length.

    delay_ms = t_syn + L / v

L: median soma -> own-presynapse geodesic distance (data/derived/skeleton_lengths.csv,
derived). v: 0.5 m/s (inferred), giant fibre DNp01 2.07 m/s (measured, Kadas et al.
2019 eNeuro, 24 h adults). t_syn: 0.5 ms (inferred). See DECISIONS session 6.
Output: data/params/conduction_delays.csv (one row per type).
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
V_DEFAULT, V_GF, T_SYN = 0.5, 2.07, 0.5      # m/s, m/s, ms  (1 m/s = 1 um/us = 1000 um/ms)


def main() -> None:
    s = pd.read_csv(ROOT / "data/derived/skeleton_lengths.csv")
    s = s[s.error.isna() & s.pre_path_p50_um.notna()].copy()
    v = np.where(s.type.eq("DNp01"), V_GF, V_DEFAULT)
    s["conduction_ms"] = s.pre_path_p50_um / (v * 1000.0)
    s["delay_ms"] = T_SYN + s.conduction_ms
    s["velocity_m_s"] = v
    s["velocity_basis"] = np.where(s.type.eq("DNp01"), "measured", "inferred")
    s["basis"] = "derived"
    s["justification"] = ("L from one skeleton (bodyId " + s.bodyId.astype(str) + ", rooted at "
                          + s.rooted + "); v " + s.velocity_basis + "; t_syn 0.5 ms inferred")
    out = ROOT / "data/params/conduction_delays.csv"
    cols = ["type", "bodyId", "pre_path_p50_um", "pre_path_p90_um", "velocity_m_s",
            "velocity_basis", "delay_ms", "basis", "justification"]
    with open(out, "w") as fh:
        fh.write("# Per-type conduction delay. Generated by scripts/conduction_delays.py.\n")
        s[cols].round(4).to_csv(fh, index=False)
    print(s.groupby("superclass").delay_ms.describe()[["count", "25%", "50%", "75%", "max"]].round(2))
    print(len(s), "types; DNp01:", s[s.type == "DNp01"][["pre_path_p50_um", "delay_ms"]].to_dict("records"))


if __name__ == "__main__":
    main()
