"""Conduction delay for cells without a skeleton-derived value (untyped cells).

Typed cells get delay = 0.5 ms + L / v from one skeleton per type
(scripts/conduction_delays.py; L = median soma->presynapse path, v 0.5 m/s).
Untyped cells had no L and fell back to the borrowed shared default (1.8 ms,
Shiu 2024), inconsistent with that rule. This infers L per untyped cell from
features every neuron has in the male-cns table: log volume, log pre and post
synapse counts, superclass. Ridge regression on log L, trained on the skeleton
table, scored by 10-fold cross-validation against a median-only baseline.
Writes data/params/conduction_delays_untyped.csv (bodyId, delay_ms, inferred).

    uv run python scripts/infer_delays.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
V_UM_PER_MS = 500.0   # 0.5 m/s, the value used for typed cells (inferred there)
T_SYN = 0.5


def design(df: pd.DataFrame, classes: list[str]) -> np.ndarray:
    cols = [np.log10(df["size"].clip(lower=1e6)), np.log10(df.pre + 1), np.log10(df.post + 1)]
    cols += [(df.superclass.fillna("") == c).astype(float) for c in classes]
    return np.column_stack(cols + [np.ones(len(df))])


def ridge(X, y, lam=1.0):
    return np.linalg.solve(X.T @ X + lam * np.eye(X.shape[1]), X.T @ y)


def main():
    s = pd.read_csv(REPO / "data/derived/skeleton_lengths.csv")
    n = pd.read_parquet(REPO / "data/cache/male_cns_neurons.parquet",
                        columns=["bodyId", "type", "superclass", "size", "pre", "post"])
    s = s.merge(n[["bodyId", "post"]], on="bodyId", how="left")
    s = s[(s.pre_path_p50_um > 0) & s["size"].notna() & s.post.notna()].reset_index(drop=True)
    classes = sorted(set(n.superclass.dropna()))
    X, y = design(s, classes), np.log10(s.pre_path_p50_um.to_numpy())
    rng = np.random.default_rng(0)
    fold = rng.integers(0, 10, len(y))
    pred = np.zeros_like(y)
    for k in range(10):
        m = fold != k
        pred[~m] = X[~m] @ ridge(X[m], y[m])
    L, Lhat, Lmed = 10 ** y, 10 ** pred, np.median(10 ** y)
    d = lambda l: T_SYN + l / V_UM_PER_MS  # noqa: E731
    err_model = np.abs(d(Lhat) - d(L))
    err_med = np.abs(d(Lmed) - d(L))
    err_default = np.abs(1.8 - d(L))
    r2 = 1 - np.sum((y - pred) ** 2) / np.sum((y - y.mean()) ** 2)
    print(f"training cells {len(y)}; CV R^2 (log L) {r2:.2f}")
    print(f"delay abs error, ms (median / p90): model {np.median(err_model):.3f} / {np.quantile(err_model, .9):.3f}; "
          f"median-L baseline {np.median(err_med):.3f} / {np.quantile(err_med, .9):.3f}; "
          f"borrowed 1.8 ms default {np.median(err_default):.3f} / {np.quantile(err_default, .9):.3f}")

    w = ridge(X, y)
    miss = n[n.type.isna() & n["size"].notna()].copy()
    miss["post"] = miss.post.fillna(0)
    # untyped cells are often fragments (a distribution shift): clip to the training range
    lo, hi = np.quantile(L, [0.05, 0.95])
    Lm = np.clip(10 ** (design(miss, classes) @ w), lo, hi)
    out = pd.DataFrame({"bodyId": miss.bodyId, "pre_path_p50_um_pred": Lm.round(1),
                        "delay_ms": d(Lm).round(3)})
    out["basis"] = "inferred"
    out["justification"] = (f"L predicted by ridge on log volume/pre/post/superclass from {len(y)} skeletons; "
                            f"10-fold CV delay abs error median {np.median(err_model):.3f} ms, "
                            f"p90 {np.quantile(err_model, .9):.3f} ms; L clipped to the training 5-95% range; then 0.5 ms + L/(0.5 m/s) as for typed cells")
    path = REPO / "data/params/conduction_delays_untyped.csv"
    with open(path, "w") as f:
        f.write("# Per-cell conduction delay for untyped cells. Generated by scripts/infer_delays.py.\n")
        out.to_csv(f, index=False)
    print(f"wrote {len(out)} untyped cells; delay median {out.delay_ms.median():.3f} ms "
          f"(range {out.delay_ms.min():.2f}-{out.delay_ms.max():.2f})")


if __name__ == "__main__":
    main()
