"""Per-motor-neuron force and torque per spike for leg motor neurons.

Measured anchor (Azevedo et al. 2020 eLife 9:e56754, Fig 4; text): single-spike
twitch force of tibia flexor motor units at the tibia, fast ~10 uN (1 neuron),
intermediate ~1 uN (2-5 neurons), slow <0.1 uN (8-9 neurons; 0.05 taken, the
middle of 0-0.1). About 15 flexor MNs in all.

Matching (inferred): in male-cns the flexor pool of each leg is `Ti flexor MN`
+ `Acc. ti flexor MN` (13 per leg on average). Within each leg's pool, cells
are ranked by EM volume (the size principle: fast = largest, lowest input
resistance, Azevedo 2020 Fig 3): rank 1 fast, ranks 2-4 intermediate, the rest
slow.

Other leg MNs (inferred): force from a power law in EM volume fitted to the
three flexor classes (log F vs log volume, class medians), applied to each MN's
own volume, clipped to [0.05, 10] uN.

Torque per spike = force x lever. Lever (derived from the flybody model, and a
simplification): the length of the segment the joint moves - coxa for
thorax-coxa, femur for coxa-trochanter, tibia for femur-tibia, tarsus for
tibia-tarsus and the long tendon. Azevedo's force was measured at the tibia,
so for the flexor this is force x tibia length (an upper bound if the probe sat
proximal to the tip).

Twitch decay (guessed per class): fast/intermediate 30 ms (half-max rise ~8.5 ms
measured; decay not reported), slow 100 ms (slow units' force "did not reach
its peak within 500 ms"; slow kinetics, value guessed).
Output: data/params/motor_forces.csv.
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AZ = "Azevedo et al. 2020 eLife 9:e56754 (Fig 4, Results)"
FORCE = {"fast": 10.0, "intermediate": 1.0, "slow": 0.05}
TAU = {"fast": 30.0, "intermediate": 30.0, "slow": 100.0}
# segment lengths (mm) measured from the compiled flybody model (scripts/motor_forces.py docstring)
SEG = {"f": dict(coxa=0.437, femur=0.697, tibia=0.510, tarsus=0.553),
       "m": dict(coxa=0.281, femur=0.830, tibia=0.668, tarsus=0.718),
       "h": dict(coxa=0.245, femur=0.779, tibia=0.715, tarsus=0.756)}
JOINT_SEG = {"ThC": "coxa", "CTr": "femur", "FTi": "tibia", "TiTa": "tarsus", "tendon": "tarsus"}


def main() -> None:
    import sys
    sys.path.insert(0, str(ROOT / "src"))
    from flyemu.neuromuscular import COUPLED_TO_JOINTS, MUSCLE_TO_ACTION, NEUROMERE_TO_LEG
    n = pd.read_parquet(ROOT / "data/cache/male_cns_neurons.parquet")
    m = n[(n.superclass == "vnc_motor") & n.somaNeuromere.isin(list(NEUROMERE_TO_LEG))].copy()
    m["muscle"] = m.type.fillna("").str.replace(r" MN$", "", regex=True)
    m = m[m.muscle.isin(list(MUSCLE_TO_ACTION) + list(COUPLED_TO_JOINTS))]
    m["leg"] = m.somaNeuromere.map(NEUROMERE_TO_LEG)
    m["joint"] = m.muscle.map(lambda s: MUSCLE_TO_ACTION.get(s, ("tendon",))[0])
    flex = m.muscle.isin(["Ti flexor", "Acc. ti flexor"])
    m["cls"] = None
    for _, g in m[flex].groupby(["somaNeuromere", "somaSide"]):
        order = g.sort_values("size", ascending=False).index
        m.loc[order[:1], "cls"] = "fast"
        m.loc[order[1:4], "cls"] = "intermediate"
        m.loc[order[4:], "cls"] = "slow"
    med = m[flex].groupby("cls")["size"].median()
    x = np.log([med[c] for c in FORCE]); y = np.log([FORCE[c] for c in FORCE])
    k, c0 = np.polyfit(x, y, 1)
    rows = []
    for r in m.itertuples():
        lever = SEG[r.leg][JOINT_SEG[r.joint]]
        if r.cls is not None:
            f, fb = FORCE[r.cls], "measured"
            tau, tb = TAU[r.cls], "guessed"
            just = (f"{r.cls} flexor unit: force measured ({AZ}); class by EM-volume rank within "
                    f"this leg's flexor pool (inferred); x tibia length {lever} mm (derived)")
            basis = "derived"
        else:
            f = float(np.clip(np.exp(c0 + k * np.log(r.size)), 0.05, 10.0))
            fb, tau, tb = "inferred", (100.0 if f < 0.3 else 30.0), "guessed"
            just = (f"size-scaled from the flexor classes: F = exp({c0:.2f}) V^{k:.2f} (V = EM "
                    f"volume), inferred; x {JOINT_SEG[r.joint]} length {lever} mm (derived)")
            basis = "inferred"
        rows.append(dict(bodyId=r.bodyId, type=r.type, leg=r.leg + r.somaSide.lower() if isinstance(r.somaSide, str) else r.leg,
                         joint=r.joint, size_vox=r.size, unit_class=r.cls or "",
                         force_uN=round(f, 4), force_basis=fb, lever_mm=lever,
                         torque_uNmm=round(f * lever, 5), twitch_tau_ms=tau, tau_basis=tb,
                         basis=basis, source=AZ, justification=just))
    df = pd.DataFrame(rows)
    out = ROOT / "data/params/motor_forces.csv"
    with open(out, "w") as fh:
        fh.write("# Per-leg-motor-neuron force/torque per spike. Generated by scripts/motor_forces.py.\n")
        df.to_csv(fh, index=False)
    print(f"size exponent k = {k:.2f}; {len(df)} leg MNs; classes:",
          df.unit_class.value_counts().to_dict())
    print(df.groupby(["joint"]).torque_uNmm.describe().round(3))


if __name__ == "__main__":
    main()
