"""Per-ORN-type absolute firing rates from Hallem & Carlson 2006, via DoOR.

Source: DoOR.data per-unit files (github ropensci/DoOR.data, commit db323a4,
data/raw/door/units/), column `Hallem.2006.EN`: single-sensillum recordings of
each Or expressed in the ab3A "empty neuron" (Hallem & Carlson 2006, Cell
125:143, 10.1016/j.cell.2006.01.050). The SFR row is the spontaneous rate;
odour rows are spike-rate changes with the SFR subtracted (DoOR dataset info),
110 odours at 10^-2 dilution.

    sfr_hz  = SFR row                                  (measured, heterologous)
    rmax_hz = SFR + max over the 110 odours             (derived)

ORN types whose DoOR units include none of the 24 Hallem receptors get the
median over covered types (inferred). Output: data/params/orn_rates.csv.
"""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = "Hallem & Carlson 2006 Cell 125:143 (via DoOR.data db323a4, Hallem.2006.EN)"


def main() -> None:
    per_unit = {}
    for f in sorted((ROOT / "data/raw/door/units").glob("*.csv")):
        d = pd.read_csv(f, sep=";", index_col=0)
        if "Hallem.2006.EN" not in d.columns:
            continue
        h = d["Hallem.2006.EN"]
        odour = d.InChIKey != "SFR"
        per_unit[f.stem] = (float(h[~odour].iloc[0]), float(h[~odour].iloc[0] + h[odour].max()),
                            int(h[odour].notna().sum()))
    tun = pd.read_csv(ROOT / "data/derived/orn_tuning_door.csv")
    units = tun.groupby("orn_type").door_unit.unique()
    n = pd.read_parquet(ROOT / "data/cache/male_cns_neurons.parquet", columns=["type"])
    orn_types = sorted(t for t in n.type.dropna().unique() if t.startswith("ORN_") and t != "ORN_V")
    rows, cov = [], []
    for t in orn_types:
        hit = [u for u in units.get(t, []) if u in per_unit]
        if hit:
            u = hit[0]
            sfr, rmax, k = per_unit[u]
            cov.append((sfr, rmax))
            rows.append(dict(orn_type=t, door_unit=u, sfr_hz=sfr, rmax_hz=rmax,
                             sfr_basis="measured", rmax_basis="derived", source=SRC,
                             justification=f"{u} in the ab3A empty neuron (heterologous: "
                             f"native neuron may differ); rmax = SFR + max of {k} odour "
                             "responses at 1e-2"))
        else:
            rows.append(dict(orn_type=t, door_unit=";".join(units.get(t, [])) or "none"))
    df = pd.DataFrame(rows)
    c = pd.DataFrame(cov, columns=["sfr", "rmax"])
    miss = df.sfr_hz.isna()
    df.loc[miss, ["sfr_hz", "rmax_hz"]] = [c.sfr.median(), c.rmax.median()]
    df.loc[miss, ["sfr_basis", "rmax_basis"]] = "inferred"
    df.loc[miss, "source"] = SRC
    df.loc[miss, "justification"] = (f"no Hallem 2006 receptor for this type: median over the "
                                     f"{len(c)} covered types (SFR range {c.sfr.min():g}-"
                                     f"{c.sfr.max():g} Hz, Rmax {c.rmax.min():g}-{c.rmax.max():g} Hz)")
    out = ROOT / "data/params/orn_rates.csv"
    with open(out, "w") as fh:
        fh.write("# Absolute ORN rates per type. Generated by scripts/orn_rates.py; see its docstring.\n")
        df.to_csv(fh, index=False)
    print(df[["orn_type", "door_unit", "sfr_hz", "rmax_hz", "sfr_basis"]].to_string())


if __name__ == "__main__":
    main()
