"""Phasic versus tonic proprioceptive drive at matched mean amplitude.

Session 1 found that uniform tonic drive to the 102 leg proprioceptors raises
motor-neuron rates into physiological range but collapses the rhythm (F5, F6).
Real proprioceptors do not fire tonically during stepping: they are modulated by
the leg's own movement, which is precisely what a body would supply.

This asks the controlled version of that question. Hold the *mean* sensory input
fixed and change only its temporal structure:

    tonic   I_s(t) = A
    phasic  I_s(t) = A * (1 + sin(2*pi*f*t + phase))

Both have time-average A. If the rhythm survives phasic drive and dies under
tonic drive, the temporal structure of sensory feedback is what matters, and an
embodied loop is required rather than optional.

This is still open loop. The modulation is prescribed, not generated by a body,
and is declared as a scaffold in every run record.
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
EXT = REPO / "external" / "Pugliese_cpg_2025"
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(EXT))

import jax  # noqa: E402
import jax.numpy as jnp  # noqa: E402
from diffrax import Dopri5, ODETerm, PIDController, SaveAt, diffeqsolve  # noqa: E402

from flyemu.provenance import RunRecord  # noqa: E402
from pugliese_conditions import build_config, metrics_for  # noqa: E402
from src.simulation.vnc_sim import (  # noqa: E402
    prepare_neuron_params, prepare_sim_params, reweight_connectivity,
)
from src.utils.sim_utils import load_wTable  # noqa: E402


def rate_equation(t, R, args):
    """Pugliese half-tanh rate equation with an added time-varying sensory term.

    Identical to the published equation when sens_amp is zero.
    """
    (dn_in, sens_mask, sens_amp, sens_freq, sens_phase, pulse_start, pulse_end,
     tau, W, threshold, a, fr_cap) = args
    on = (t >= pulse_start) & (t <= pulse_end)
    # sens_phase is per neuron, so antagonist groups can be driven in antiphase
    modulation = jnp.where(
        sens_freq > 0,
        1.0 + jnp.sin(2 * jnp.pi * sens_freq * t + sens_phase),
        1.0,
    )
    I = dn_in * on + sens_mask * sens_amp * modulation * on
    total = I + jnp.dot(W, R)
    activation = jnp.maximum(fr_cap * jnp.tanh((a / fr_cap) * (total - threshold)), 0)
    return (activation - R) / tau


def simulate(W, tau, a, threshold, fr_cap, dn_in, sens_mask, sens_amp,
             sens_freq, sens_phase, sp) -> jnp.ndarray:
    sol = diffeqsolve(
        ODETerm(rate_equation), Dopri5(), 0.0, sp.T, sp.dt,
        jnp.zeros(W.shape[1]),
        args=(dn_in, sens_mask, sens_amp, sens_freq, sens_phase,
              sp.pulse_start, sp.pulse_end, tau, W, threshold, a, fr_cap),
        saveat=SaveAt(ts=sp.t_axis),
        stepsize_controller=PIDController(rtol=sp.r_tol, atol=sp.a_tol),
        max_steps=200000, throw=False,
    )
    R = jnp.transpose(sol.ys)
    R = jnp.where(jnp.isfinite(R), R, 0.0)
    return jnp.clip(R, 0.0, 1000.0)



def _append_row(out_dir: Path, row: dict) -> None:
    """Write each replicate as it finishes so a killed run keeps its results."""
    f = out_dir / "metrics_partial.csv"
    df = pd.DataFrame([row])
    df.to_csv(f, mode="a", header=not f.exists(), index=False)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sensory-amp", type=float, required=True)
    ap.add_argument("--freq", type=float, required=True,
                    help="sensory modulation frequency in Hz; 0 means tonic")
    ap.add_argument("--proprio-cholinergic", action="store_true",
                    help="force proprioceptors excitatory, per published "
                         "physiology; see finding F10")
    ap.add_argument("--phase-groups", type=int, default=1,
                    help="split the proprioceptors into K groups with phases "
                         "evenly spaced over one cycle. K=1 drives them all "
                         "together, which is unrealistic; K=2 puts antagonist "
                         "groups in antiphase, as flexion- and extension-tuned "
                         "position sensors actually are.")
    ap.add_argument("--phase", type=float, default=0.0)
    ap.add_argument("--replicates", type=int, default=8)
    ap.add_argument("--rtol", type=float, default=2e-6)
    ap.add_argument("--atol", type=float, default=5e-9)
    ap.add_argument("--out", default=str(REPO / "runs"))
    ap.add_argument("--save-traces", action="store_true")
    args = ap.parse_args()

    kind = "tonic" if args.freq == 0 else f"phasic{args.freq:g}Hz"
    if args.phase_groups > 1:
        kind += f"-g{args.phase_groups}"
    if args.proprio_cholinergic:
        kind += "-propACh"
    run_id = f"phasic-A{args.sensory_amp:g}-{kind}-n{args.replicates}"
    out_dir = Path(args.out) / run_id
    rec = RunRecord(run_id, out_dir,
                    description="Phasic vs tonic proprioceptive drive, matched mean amplitude")
    rec.add_code("pugliese_repo", EXT)

    cfg = build_config()
    cfg.experiment.n_replicates = args.replicates
    cfg.sim.rtol, cfg.sim.atol = args.rtol, args.atol
    wTable = load_wTable(cfg.experiment.dfPath)

    prop = wTable.loc[wTable["subclass"].isin(
        ["chordotonal organ", "hair plate", "campaniform sensilla"])].index.values
    rec.add_input("W", cfg.experiment.wPath)
    rec.add_input("wTable", cfg.experiment.dfPath)
    rec.add_config(cfg)
    rec.rec["condition_notes"] = {
        "sensory_amp_mean": args.sensory_amp,
        "modulation": kind,
        "phase_groups": args.phase_groups,
        "proprioceptors_driven": int(len(prop)),
        "breakdown": wTable.loc[prop, "subclass"].value_counts().to_dict(),
    }
    rec.declare_scaffold(
        "Tonic current imposed on a descending neuron; reproduces an optogenetic "
        "experiment, not spontaneous behaviour.")
    rec.declare_scaffold(
        f"Proprioceptive drive is prescribed ({kind}, mean amplitude "
        f"{args.sensory_amp}), not generated by a body. No measured spike-rate "
        f"calibration exists for these afferents.")
    rec.declare_scaffold(
        "Synaptic weight is synapse count times a single global multiplier, with "
        "sign from EM transmitter prediction. Not measured efficacy.")

    np_ = prepare_neuron_params(cfg, wTable)
    if args.proprio_cholinergic:
        Wn = np.array(np_.W, copy=True)
        flipped = int((Wn[prop, :] < 0).any(axis=1).sum())
        Wn[prop, :] = np.abs(Wn[prop, :])
        np_ = np_._replace(W=jnp.asarray(Wn))
        rec.rec["proprio_cholinergic"] = {"neurons_flipped": flipped}
        rec.declare_scaffold(
            "Proprioceptor signs overridden to excitatory on published "
            "physiology rather than the EM classifier (finding F10).")
        print(f"  forced {flipped}/{len(prop)} proprioceptors excitatory")
    n = int(np_.W.shape[0])
    sp = prepare_sim_params(cfg, 1, n)
    mn_idx = np.asarray(np_.mn_idxs)
    sens_mask = jnp.zeros(n).at[jnp.asarray(prop)].set(1.0)
    # per-neuron phase: group g of K gets phase 2*pi*g/K
    grp = np.arange(len(prop)) % max(1, args.phase_groups)
    phase_vec = np.zeros(n)
    phase_vec[prop] = args.phase + 2 * np.pi * grp / max(1, args.phase_groups)
    phase_vec = jnp.asarray(phase_vec)
    Wr = reweight_connectivity(np_.W, sp.exc_multiplier, sp.inh_multiplier)

    rows = []
    for i in range(args.replicates):
        t0 = time.time()
        R = simulate(Wr, np_.tau[i], np_.a[i], np_.threshold[i], np_.fr_cap[i],
                     np_.input_currents[0][i], sens_mask, args.sensory_amp,
                     args.freq, phase_vec, sp)
        R.block_until_ready()
        Rn = np.asarray(R)
        m = metrics_for(Rn, wTable, mn_idx, sp.t_axis)
        m["replicate"] = i
        m["sim_seconds"] = round(time.time() - t0, 2)
        rows.append(m)
        _append_row(out_dir, m)
        print(f"  rep {i}: activeMN={m['n_active_mn']:3d} osc={m['oscillation_score_mn']:.3f} "
              f"f={m['oscillation_freq_hz_mn']:.2f}Hz peakMN={m['mn_peak_rate_median_hz']:.1f}Hz "
              f"({m['sim_seconds']}s)", flush=True)
        if i == 0 and args.save_traces:
            np.savez_compressed(out_dir / "R_replicate0.npz",
                                R=Rn.astype(np.float32), t=np.asarray(sp.t_axis),
                                mn_idx=mn_idx)

    df = pd.DataFrame(rows)
    df["sensory_amp"] = args.sensory_amp
    df["freq_hz"] = args.freq
    df["phase_groups"] = args.phase_groups
    df.to_csv(out_dir / "metrics.csv", index=False)
    for c in ("oscillation_score_mn", "oscillation_freq_hz_mn", "n_active_mn",
              "mn_peak_rate_median_hz", "mn_peak_rate_max_hz"):
        rec.result(c, {"mean": float(df[c].mean()),
                       "sd": float(df[c].std(ddof=1)) if len(df) > 1 else 0.0})
    rec.finish()
    print(f"[{run_id}] rhythm {df['oscillation_score_mn'].mean():.3f} | "
          f"peak MN {df['mn_peak_rate_median_hz'].mean():.1f} Hz | "
          f"{rec.rec['wall_seconds']}s")


if __name__ == "__main__":
    main()
